parameters:
    maintaince: false
    base_url: '%env(BASE_URL)%'
    acp_url: '%env(ACP_URL)%'
    version: 0.0.1
    mailer.dns: 'sendmail://default'
    mail.validation: false
    mail.address: example@mail.com
    mail.username: Admin
