<?php

/**
*   This file was generated by "OneBB instalation wizard"
**/

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '23263642ff1d444f70f732146c664f81',
  'DATABASE_URL' => 'mysql://user:pass@localhost:3306/base?serverVersion=5.7',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem', 
  'JWT_PASSPHRASE' => '53fe0d8dbbc8ea8e1f29d4e175945af4', 
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
  'LOCK_DSN' => 'semaphore',
  'DOCS' => '0',
  'ACP_URL' => 'acp',
  'BASE_URL'=> '/',
);
